export const DOC_TYPES = {
  QUOTE: "quote",
  DELIVERY_NOTE: "delivery_note",
  INVOICE: "invoice",
} as const;

export const DOC_STATUSES = {
  DRAFT: "draft",
  NOT_SENT: "not_sent",
  SENT: "sent",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  PAID: "paid",
  PARTIALLY_PAID: "partially_paid",
  CANCELLED: "cancelled",
} as const;

export const STATUS_TRANSITIONS: Record<string, string[]> = {
  [DOC_STATUSES.DRAFT]: [DOC_STATUSES.NOT_SENT],
  [DOC_STATUSES.NOT_SENT]: [DOC_STATUSES.SENT, DOC_STATUSES.CANCELLED],
  [DOC_STATUSES.SENT]: [DOC_STATUSES.ACCEPTED, DOC_STATUSES.REJECTED, DOC_STATUSES.CANCELLED],
  [DOC_STATUSES.ACCEPTED]: [DOC_STATUSES.PAID, DOC_STATUSES.PARTIALLY_PAID, DOC_STATUSES.CANCELLED],
  [DOC_STATUSES.PARTIALLY_PAID]: [DOC_STATUSES.PAID, DOC_STATUSES.CANCELLED],
  [DOC_STATUSES.REJECTED]: [DOC_STATUSES.CANCELLED],
  [DOC_STATUSES.PAID]: [],
  [DOC_STATUSES.CANCELLED]: [],
};

// Map backend status values to i18n keys
export const STATUS_I18N_MAP: Record<string, string> = {
  [DOC_STATUSES.DRAFT]: "DRAFT",
  [DOC_STATUSES.NOT_SENT]: "NOT_SENT",
  [DOC_STATUSES.SENT]: "SENT",
  [DOC_STATUSES.ACCEPTED]: "ACCEPTED",
  [DOC_STATUSES.REJECTED]: "REJECTED",
  [DOC_STATUSES.PAID]: "PAID",
  [DOC_STATUSES.PARTIALLY_PAID]: "PARTIAL",
  [DOC_STATUSES.CANCELLED]: "CANCELLED",
};

export const TYPE_I18N_MAP: Record<string, string> = {
  [DOC_TYPES.QUOTE]: "QUOTE",
  [DOC_TYPES.DELIVERY_NOTE]: "DELIVERY_NOTE",
  [DOC_TYPES.INVOICE]: "INVOICE",
};

export const TAX_RATE = 0.21;
